baseURL = "http://dev.l1x.be/"
languageCode = "en-us"
title = "l1x/dev"
removepathaccents = true
preserveTaxonomyNames = true
paginate = 10

[params]
  contentTypeName = "posts"
  description = "Thoughts on DevOps, Unix, Erlang, Fsharp, big Data and high performance topics by l1x"

[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"
  projects = "/projects/:slug/"
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 2

